### ISSUE TITLE
Npm output should not be hidden

### ISSUE THREAD

**Issue by adriaanthomas** [vvo/npm-pkgr#17]
When running `npm-pkgr` on our build server, it is far easier to analyse problems if we have the standard `npm` console output.

Is there a particular reason this has been suppressed? If so, does it make sense to add a command-line parameter?

**Comment by vvo** [comment]
Why not adding a logger to the programmatic interface and then to the command line client yes.

Something like --show-npm-log showNpmLog: true/false

?

The code doing the install is right here https://github.com/vvo/npm-pkgr/blob/master/lib/install-npm.js

Submit a PR

**Comment by adriaanthomas** [comment]
OK thanks, I will. It might take me a little bit to find the time, but a PR is definitely on its way.
