### ISSUE TITLE
work with docker container ?

### ISSUE THREAD

**Issue by lili21** [vvo/npm-pkgr#26]
will the cache still be there ?

**Comment by vvo** [comment]
I have no idea, you have to try for yourself

**Comment by lili21** [comment]
It works, weird. cause of those lockfiles ? Just be curious, Why you need to lock those file ?

**Comment by vvo** [comment]
Lock files are required in case the process fails or concurrent usage on the same system, so we can know if everything went well or not, and what is currently being worked.

Also nowadays yarn is a prettier solution to the "fast npm installs" issue

**Comment by lili21** [comment]
Indeed. Actually, I am trying to cache the `yarn install` results in container.

**Comment by vvo** [comment]
Do you think there's a big optimization in trying to cache yarn install results? I would say yarn is capapble of doing the same as npm-pkgr

**Comment by lili21** [comment]
I think yarn just cached every single package instead of node_modules. 
If I remove the node_modules, yarn will link every dependencies, and that is not fast as expecting.

**Comment by lili21** [comment]
![2016-12-01 5 53 00](https://cloud.githubusercontent.com/assets/4456380/20789115/47fc9556-b7ee-11e6-8b2c-6b76983ebb54.png)

**Comment by lili21** [comment]
sometimes it will take like 70, 80 seconds.

**Comment by vvo** [comment]
My default yarn install is very fast (not using npm pkgr etc), this is more of a yarn issue here I believe? If so, close the issue. Good luck
