### ISSUE TITLE
add a prune feature to avoid filling the disk

### ISSUE THREAD

**Issue by Yvem** [vvo/npm-pkgr#8]
When used over a long time, .npm-pkgr ends up eating all disk space :-( (and manual cleanup takes 2h+ since cache consists of billions of small files)

A useful feature would be the removing of non recently used cached npm install.

Suggestion : `npm-pkgr prune` would remove all cached installs older than a month.

**Comment by vvo** [comment]
Good idea! Will accept a PR :D The whole project is tested so it should not be a very big deal to add it.

Let me know @Yvem if you plan to do it.

**Comment by moll** [comment]
I presume he hasn't. ^_^

**Comment by vvo** [comment]
Nope :)

**Comment by Yvem** [comment]
@vvo I don't plan to do it :-P

**Comment by vvo** [comment]
no prob :dancer:

**Comment by vvo** [comment]
Was done and released as 0.3.0
